
namespace App\Models;


use App\Models\Base\<?=$modelName?>Base;

/**
 * @package App\Models
 * Class <?=$modelName?>

 *
 * Generated by 'php artisan model:create'
 */
class <?=$modelName?> extends <?=$modelName?>Base
{

}

