<?php

namespace App\Models;


use App\Models\Base\AdCommandBase;

/**
 * @package App\Models
 * Class AdCommand
 *
 * Generated by 'php artisan model:create'
 */
class AdCommand extends AdCommandBase
{

}

