<?php

namespace App\Models;


use App\Models\Base\AdDataAlertBase;

/**
 * @package App\Models
 * Class AdDataAlert
 *
 * Generated by 'php artisan model:create'
 */
class AdDataAlert extends AdDataAlertBase
{

}

