<?php

namespace App\Models;


use App\Models\Base\AdDeviceTypeBase;

/**
 * @package App\Models
 * Class AdDeviceType
 *
 * Generated by 'php artisan model:create'
 */
class AdDeviceType extends AdDeviceTypeBase
{

}

