<?php

namespace App\Models;


use App\Models\Base\AdDeviceBase;

/**
 * @package App\Models
 * Class AdDevice
 *
 * Generated by 'php artisan model:create'
 */
class AdDevice extends AdDeviceBase
{

}

