<?php

namespace App\Models;


use App\Models\Base\AdDeviceFieldBase;

/**
 * @package App\Models
 * Class AdDeviceField
 *
 * Generated by 'php artisan model:create'
 */
class AdDeviceField extends AdDeviceFieldBase
{

}

