<?php

namespace App\Models;


use App\Models\Base\AdDeviceAlertConfigBase;

/**
 * @package App\Models
 * Class AdDeviceAlertConfig
 *
 * Generated by 'php artisan model:create'
 */
class AdDeviceAlertConfig extends AdDeviceAlertConfigBase
{

}

