<?php

namespace App\Models;


use App\Models\Base\AdStationBase;

/**
 * @package App\Models
 * Class AdStation
 *
 * Generated by 'php artisan model:create'
 */
class AdStation extends AdStationBase
{

}

