<?php

namespace App\Models;


use App\Models\Base\DtDataBase;

/**
 * @package App\Models
 * Class DtData
 *
 * Generated by 'php artisan model:create'
 */
class DtData extends DtDataBase
{
    public function setDeviceId($deviceId) {
        $this->table = "dt_data_{$deviceId}";
    }

}

