<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdCommandBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $command_id    
 * @property $command_type    
 * @property $command_status    
 * @property $target_id    
 * @property $command_p1    
 * @property $command_p2    
 * @property $command_p3    
 * @property $command_p4    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class AdCommandBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_command';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'command_id';



}

