<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdDataAlertBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $alert_id    
 * @property $device_id    
 * @property $data_id    
 * @property $is_hide    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class AdDataAlertBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_data_alert';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'alert_id';



}

