<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdDeviceAlertConfigBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $config_id    
 * @property $device_id    
 * @property $field_id    
 * @property $alert_type    
 * @property $alert_value1    
 * @property $alert_value2    
 * @property $alert_status    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class AdDeviceAlertConfigBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_device_alert_config';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'config_id';



}

