<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdDeviceFieldBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $field_id    
 * @property $type_id    
 * @property $field_type    
 * @property $field_name    
 * @property $field_title    
 * @property $field_desc    
 * @property $field_unit    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class AdDeviceFieldBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_device_field';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'field_id';



}

