<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdGrantBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $grant_id    
 * @property $user_id    
 * @property $device_id    
 */
class AdGrantBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_grant';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'grant_id';



}

