<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdStationBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $station_id    
 * @property $station_name    
 * @property $station_desc    
 * @property $station_address    
 * @property $station_type    
 * @property $group_id    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class AdStationBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_station';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'station_id';



}

