<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class AdUserBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $user_id    
 * @property $user_name    
 * @property $user_nick    
 * @property $user_password    
 * @property $group_id    
 */
class AdUserBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'ad_user';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'user_id';



}

