<?php

namespace App\Models\Base;

/**
 * @package App\Models
 * Class DtDataBase
 *
 * Generated by 'php artisan model:create'
 * Properties as follows
 * @property $data_id    
 * @property $data_time    
 * @property $status    
 * @property $create_time    
 * @property $update_time    
 */
class DtDataBase extends BaseModel
{
    /**
     * Table name
     */
    protected $table = 'dt_data';

    /**
     * Table primary-key
     */
    protected $primaryKey = 'data_id';



}

